### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [TahjDev/TRT#2]
- [x] Is the `name` column on the Users table actually `username`? 
- [x] If you are going to be able to save places in videos, you need to account for that somewhere (i.e. a boolean of whether something has been started or not - and if it has, a time note for where the user currently is in the video) 
- [x] The Anime's should hold a reference to their genre so that users can filter by genre to find certain anime 
- [x] Create a way to group anime that go together (i.e. a series of episodes are all part of the same series) - how will that be connected. The anime's table is not currently sufficient.
- [x] Users can also leave comments (apologies as I only just realized that) - please add it to your MVP List as well as add a comments table to your Schema 

Let me know if you have any questions!

**Comment by TahjDev** [comment]
Paloma about the anime should hold a reference to genre. I did a joins table for that one the filter one? Is that not how I should do it. I thought that would be better since some animes may be in multiple genres

**Comment by PLUCS2** [comment]
That looks good and is the correct way to do it for a many to many relationship - let me know if you have any other questions!

**Comment by TahjDev** [comment]
I will and thanks for being so responsive. I'll get to fixing the rest and thank you for the critiques
